lang: en
check-update: true
check-interval-ticks: 40

conditions:
  ignore-in-vehicle: true
  ignore-flying: true
  ignore-in-water: true
  ignored-gamemodes:
    - CREATIVE
    - SPECTATOR

worlds:
  mode: blacklist
  list:
    - "world_nether"
    - "world_the_end"

biomes:
  mode: blacklist
  list:
    - "minecraft:desert"
    - "minecraft:desert_lakes"
    - "minecraft:savanna"
    - "minecraft:savanna_plateau"
    - "minecraft:windswept_savanna"
    - "minecraft:badlands"
    - "minecraft:wooded_badlands"
    - "minecraft:eroded_badlands"

effects:
  rain:
    enabled: true
    type: SLOW
    level: 0
    duration-ticks: 80

  thunder:
    enabled: true
    type: SLOW
    level: 1
    duration-ticks: 80

  snow:
    enabled: false
    type: SLOW
    level: 0
    duration-ticks: 60
